services:
  web:
    build: .
    ports: 
        - "8082:5000"
    env_file: 
        - .env
    depends_on: 
        - mysql

  mysql:
    image: mysql:8.0
   
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dashboard
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes: 
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

